name = "ThreeTankSystem"
uuid = "26250889-8995-4aee-89f4-198ce54e80c4"
version = "0.1.0"
authors = ["basta <jsembasta@gmail.com>"]

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
ControlSystems = "1.15.1"
GLMakie = "0.13.8"
HiGHS = "1.20.1"
JuMP = "1.29.3"
ModelingToolkit = "11.4.0"
ModelingToolkitStandardLibrary = "2.26.0"
OrdinaryDiffEq = "6.105.0"
Plots = "1.41.3"
Pluto = "0.20.21"
Revise = "3.12.3"
